/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AdminAppMenusMoveMenuBody,
  AdminAppsListApps200,
  AdminAppsListAppsParams,
  AdminAppsSetAppStatusBody,
  AdminTenantsListTenants200,
  AdminTenantsListTenantsParams,
  ApiKey,
  App,
  AppPublicInfo,
  AuthorizeCodeRequest,
  CreateApiKeyRequest,
  CreateApiKeyResponse,
  CreateAppRequest,
  CreateMenuRequest,
  CreateRoleRequest,
  CreateTenantRequest,
  CreateUserRequest,
  CurrentUser,
  LoginRequest,
  LoginResponse,
  MeGetMyMenus200,
  Menu,
  OAuthAuthorize200,
  OidcCallbackRequest,
  ReorderMenuRequest,
  Role,
  RoleMenuGrant,
  SetRoleMenusRequest,
  SwitchTenantResponse,
  Tenant,
  TenantApiKeysListApiKeys200,
  TenantApiKeysListApiKeysParams,
  TenantAuditExportAuditEvents200,
  TenantAuditExportAuditEventsBody,
  TenantAuditGetRetentionPolicy200,
  TenantAuditListAuditEvents200,
  TenantAuditListAuditEventsByUser200,
  TenantAuditListAuditEventsByUserParams,
  TenantAuditListAuditEventsParams,
  TenantAuditSetRetentionPolicy200,
  TenantAuditSetRetentionPolicyBody,
  TenantMembership,
  TenantRolesListRoles200,
  TenantRolesListRolesParams,
  TenantRolesSetPermissionsBody,
  TenantUsersAssignRolesBody,
  TenantUsersChangeUserStatusBody,
  TenantUsersInviteUserBody,
  TenantUsersListUsers200,
  TenantUsersListUsersParams,
  TokenRequest,
  TokenResponse,
  UpdateAppRequest,
  UpdateMenuRequest,
  UpdateRoleRequest,
  UpdateTenantRequest,
  UpdateUserRequest,
  User
} from './handlers.msw.schemas';




  export const adminAppsListApps = <TData = AxiosResponse<AdminAppsListApps200>>(
    params?: AdminAppsListAppsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/admin/apps`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const adminAppsCreateApp = <TData = AxiosResponse<App>>(
    createAppRequest: CreateAppRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/admin/apps`,
      createAppRequest,options
    );
  }

export const adminAppsGetApp = <TData = AxiosResponse<App>>(
    appId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/admin/apps/${appId}`,options
    );
  }

export const adminAppsUpdateApp = <TData = AxiosResponse<App>>(
    appId: string,
    updateAppRequest: UpdateAppRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/v1/admin/apps/${appId}`,
      updateAppRequest,options
    );
  }

export const adminAppsDeleteApp = <TData = AxiosResponse<void>>(
    appId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/admin/apps/${appId}`,options
    );
  }

export const adminAppMenusListMenus = <TData = AxiosResponse<Menu[]>>(
    appId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/admin/apps/${appId}/menus`,options
    );
  }

export const adminAppMenusCreateMenu = <TData = AxiosResponse<Menu>>(
    appId: string,
    createMenuRequest: CreateMenuRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/admin/apps/${appId}/menus`,
      createMenuRequest,options
    );
  }

export const adminAppMenusGetMenu = <TData = AxiosResponse<Menu>>(
    appId: string,
    menuId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/admin/apps/${appId}/menus/${menuId}`,options
    );
  }

export const adminAppMenusUpdateMenu = <TData = AxiosResponse<Menu>>(
    appId: string,
    menuId: string,
    updateMenuRequest: UpdateMenuRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/v1/admin/apps/${appId}/menus/${menuId}`,
      updateMenuRequest,options
    );
  }

export const adminAppMenusDeleteMenu = <TData = AxiosResponse<void>>(
    appId: string,
    menuId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/admin/apps/${appId}/menus/${menuId}`,options
    );
  }

export const adminAppMenusMoveMenu = <TData = AxiosResponse<Menu>>(
    appId: string,
    menuId: string,
    adminAppMenusMoveMenuBody: AdminAppMenusMoveMenuBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/v1/admin/apps/${appId}/menus/${menuId}/parent`,
      adminAppMenusMoveMenuBody,options
    );
  }

export const adminAppMenusReorderMenus = <TData = AxiosResponse<Menu[]>>(
    appId: string,
    menuId: string,
    reorderMenuRequest: ReorderMenuRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/v1/admin/apps/${appId}/menus/${menuId}/reorder`,
      reorderMenuRequest,options
    );
  }

export const adminAppsSetAppStatus = <TData = AxiosResponse<App>>(
    appId: string,
    adminAppsSetAppStatusBody: AdminAppsSetAppStatusBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/v1/admin/apps/${appId}/status`,
      adminAppsSetAppStatusBody,options
    );
  }

export const adminTenantsListTenants = <TData = AxiosResponse<AdminTenantsListTenants200>>(
    params?: AdminTenantsListTenantsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/admin/tenants`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const adminTenantsCreateTenant = <TData = AxiosResponse<Tenant>>(
    createTenantRequest: CreateTenantRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/admin/tenants`,
      createTenantRequest,options
    );
  }

export const adminTenantsGetTenant = <TData = AxiosResponse<Tenant>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/admin/tenants/${id}`,options
    );
  }

export const adminTenantsUpdateTenant = <TData = AxiosResponse<Tenant>>(
    id: string,
    updateTenantRequest: UpdateTenantRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/v1/admin/tenants/${id}`,
      updateTenantRequest,options
    );
  }

export const adminTenantsDeleteTenant = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/admin/tenants/${id}`,options
    );
  }

export const appsGetApp = <TData = AxiosResponse<AppPublicInfo>>(
    code: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/apps/${code}`,options
    );
  }

export const authLogin = <TData = AxiosResponse<LoginResponse>>(
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/auth/login`,
      loginRequest,options
    );
  }

export const authLogout = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/auth/logout`,undefined,options
    );
  }

export const authOidcCallback = <TData = AxiosResponse<TokenResponse>>(
    oidcCallbackRequest: OidcCallbackRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/auth/oidc/callback`,
      oidcCallbackRequest,options
    );
  }

export const authRefreshToken = <TData = AxiosResponse<TokenResponse>>(
    tokenRequest: TokenRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/auth/refresh`,
      tokenRequest,options
    );
  }

export const meWhoami = <TData = AxiosResponse<CurrentUser>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/me`,options
    );
  }

export const meGetMyMenus = <TData = AxiosResponse<MeGetMyMenus200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/me/menus`,options
    );
  }

export const meListMyTenants = <TData = AxiosResponse<TenantMembership[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/me/tenants`,options
    );
  }

export const meSwitchTenant = <TData = AxiosResponse<SwitchTenantResponse>>(
    tenantId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/me/tenants/${tenantId}/switch`,undefined,options
    );
  }

export const oAuthAuthorize = <TData = AxiosResponse<OAuthAuthorize200>>(
    authorizeCodeRequest: AuthorizeCodeRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/oauth/authorize`,
      authorizeCodeRequest,options
    );
  }

export const oAuthToken = <TData = AxiosResponse<TokenResponse>>(
    tokenRequest: TokenRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/oauth/token`,
      tokenRequest,options
    );
  }

export const tenantApiKeysListApiKeys = <TData = AxiosResponse<TenantApiKeysListApiKeys200>>(
    tenantId: string,
    params?: TenantApiKeysListApiKeysParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/tenants/${tenantId}/api-keys`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const tenantApiKeysCreateApiKey = <TData = AxiosResponse<CreateApiKeyResponse>>(
    tenantId: string,
    createApiKeyRequest: CreateApiKeyRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/tenants/${tenantId}/api-keys`,
      createApiKeyRequest,options
    );
  }

export const tenantApiKeysRevokeApiKey = <TData = AxiosResponse<ApiKey>>(
    tenantId: string,
    keyId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/tenants/${tenantId}/api-keys/${keyId}/revoke`,undefined,options
    );
  }

export const tenantApiKeysRotateApiKey = <TData = AxiosResponse<CreateApiKeyResponse>>(
    tenantId: string,
    keyId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/tenants/${tenantId}/api-keys/${keyId}/rotate`,undefined,options
    );
  }

export const tenantAuditListAuditEvents = <TData = AxiosResponse<TenantAuditListAuditEvents200>>(
    tenantId: string,
    params?: TenantAuditListAuditEventsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/tenants/${tenantId}/audit-events`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const tenantAuditListAuditEventsByUser = <TData = AxiosResponse<TenantAuditListAuditEventsByUser200>>(
    tenantId: string,
    userId: string,
    params?: TenantAuditListAuditEventsByUserParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/tenants/${tenantId}/audit-events/by-user/${userId}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const tenantAuditExportAuditEvents = <TData = AxiosResponse<TenantAuditExportAuditEvents200>>(
    tenantId: string,
    tenantAuditExportAuditEventsBody: TenantAuditExportAuditEventsBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/tenants/${tenantId}/audit-events/export`,
      tenantAuditExportAuditEventsBody,options
    );
  }

export const tenantAuditGetRetentionPolicy = <TData = AxiosResponse<TenantAuditGetRetentionPolicy200>>(
    tenantId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/tenants/${tenantId}/audit-events/retention`,options
    );
  }

export const tenantAuditSetRetentionPolicy = <TData = AxiosResponse<TenantAuditSetRetentionPolicy200>>(
    tenantId: string,
    tenantAuditSetRetentionPolicyBody: TenantAuditSetRetentionPolicyBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/v1/tenants/${tenantId}/audit-events/retention`,
      tenantAuditSetRetentionPolicyBody,options
    );
  }

export const tenantRolesListRoles = <TData = AxiosResponse<TenantRolesListRoles200>>(
    tenantId: string,
    params?: TenantRolesListRolesParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/tenants/${tenantId}/roles`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const tenantRolesCreateRole = <TData = AxiosResponse<Role>>(
    tenantId: string,
    createRoleRequest: CreateRoleRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/tenants/${tenantId}/roles`,
      createRoleRequest,options
    );
  }

export const tenantRolesGetRole = <TData = AxiosResponse<Role>>(
    tenantId: string,
    roleId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/tenants/${tenantId}/roles/${roleId}`,options
    );
  }

export const tenantRolesUpdateRole = <TData = AxiosResponse<Role>>(
    tenantId: string,
    roleId: string,
    updateRoleRequest: UpdateRoleRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/v1/tenants/${tenantId}/roles/${roleId}`,
      updateRoleRequest,options
    );
  }

export const tenantRolesDeleteRole = <TData = AxiosResponse<void>>(
    tenantId: string,
    roleId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/tenants/${tenantId}/roles/${roleId}`,options
    );
  }

export const tenantRoleMenusListRoleMenus = <TData = AxiosResponse<RoleMenuGrant>>(
    tenantId: string,
    roleId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/tenants/${tenantId}/roles/${roleId}/menus`,options
    );
  }

export const tenantRoleMenusSetRoleMenus = <TData = AxiosResponse<RoleMenuGrant>>(
    tenantId: string,
    roleId: string,
    setRoleMenusRequest: SetRoleMenusRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/v1/tenants/${tenantId}/roles/${roleId}/menus`,
      setRoleMenusRequest,options
    );
  }

export const tenantRoleMenusClearRoleMenus = <TData = AxiosResponse<void>>(
    tenantId: string,
    roleId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/tenants/${tenantId}/roles/${roleId}/menus`,options
    );
  }

export const tenantRolesSetPermissions = <TData = AxiosResponse<Role>>(
    tenantId: string,
    roleId: string,
    tenantRolesSetPermissionsBody: TenantRolesSetPermissionsBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/v1/tenants/${tenantId}/roles/${roleId}/permissions`,
      tenantRolesSetPermissionsBody,options
    );
  }

export const tenantUsersListUsers = <TData = AxiosResponse<TenantUsersListUsers200>>(
    tenantId: string,
    params?: TenantUsersListUsersParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/tenants/${tenantId}/users`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const tenantUsersCreateUser = <TData = AxiosResponse<User>>(
    tenantId: string,
    createUserRequest: CreateUserRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/tenants/${tenantId}/users`,
      createUserRequest,options
    );
  }

export const tenantUsersInviteUser = <TData = AxiosResponse<User>>(
    tenantId: string,
    tenantUsersInviteUserBody: TenantUsersInviteUserBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/tenants/${tenantId}/users/invitations`,
      tenantUsersInviteUserBody,options
    );
  }

export const tenantUsersGetUser = <TData = AxiosResponse<User>>(
    tenantId: string,
    userId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/tenants/${tenantId}/users/${userId}`,options
    );
  }

export const tenantUsersUpdateUser = <TData = AxiosResponse<User>>(
    tenantId: string,
    userId: string,
    updateUserRequest: UpdateUserRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/v1/tenants/${tenantId}/users/${userId}`,
      updateUserRequest,options
    );
  }

export const tenantUsersDeleteUser = <TData = AxiosResponse<void>>(
    tenantId: string,
    userId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/tenants/${tenantId}/users/${userId}`,options
    );
  }

export const tenantUsersAssignRoles = <TData = AxiosResponse<User>>(
    tenantId: string,
    userId: string,
    tenantUsersAssignRolesBody: TenantUsersAssignRolesBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/v1/tenants/${tenantId}/users/${userId}/roles`,
      tenantUsersAssignRolesBody,options
    );
  }

export const tenantUsersChangeUserStatus = <TData = AxiosResponse<User>>(
    tenantId: string,
    userId: string,
    tenantUsersChangeUserStatusBody: TenantUsersChangeUserStatusBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/v1/tenants/${tenantId}/users/${userId}/status`,
      tenantUsersChangeUserStatusBody,options
    );
  }

export type AdminAppsListAppsResult = AxiosResponse<AdminAppsListApps200>
export type AdminAppsCreateAppResult = AxiosResponse<App>
export type AdminAppsGetAppResult = AxiosResponse<App>
export type AdminAppsUpdateAppResult = AxiosResponse<App>
export type AdminAppsDeleteAppResult = AxiosResponse<void>
export type AdminAppMenusListMenusResult = AxiosResponse<Menu[]>
export type AdminAppMenusCreateMenuResult = AxiosResponse<Menu>
export type AdminAppMenusGetMenuResult = AxiosResponse<Menu>
export type AdminAppMenusUpdateMenuResult = AxiosResponse<Menu>
export type AdminAppMenusDeleteMenuResult = AxiosResponse<void>
export type AdminAppMenusMoveMenuResult = AxiosResponse<Menu>
export type AdminAppMenusReorderMenusResult = AxiosResponse<Menu[]>
export type AdminAppsSetAppStatusResult = AxiosResponse<App>
export type AdminTenantsListTenantsResult = AxiosResponse<AdminTenantsListTenants200>
export type AdminTenantsCreateTenantResult = AxiosResponse<Tenant>
export type AdminTenantsGetTenantResult = AxiosResponse<Tenant>
export type AdminTenantsUpdateTenantResult = AxiosResponse<Tenant>
export type AdminTenantsDeleteTenantResult = AxiosResponse<void>
export type AppsGetAppResult = AxiosResponse<AppPublicInfo>
export type AuthLoginResult = AxiosResponse<LoginResponse>
export type AuthLogoutResult = AxiosResponse<void>
export type AuthOidcCallbackResult = AxiosResponse<TokenResponse>
export type AuthRefreshTokenResult = AxiosResponse<TokenResponse>
export type MeWhoamiResult = AxiosResponse<CurrentUser>
export type MeGetMyMenusResult = AxiosResponse<MeGetMyMenus200>
export type MeListMyTenantsResult = AxiosResponse<TenantMembership[]>
export type MeSwitchTenantResult = AxiosResponse<SwitchTenantResponse>
export type OAuthAuthorizeResult = AxiosResponse<OAuthAuthorize200>
export type OAuthTokenResult = AxiosResponse<TokenResponse>
export type TenantApiKeysListApiKeysResult = AxiosResponse<TenantApiKeysListApiKeys200>
export type TenantApiKeysCreateApiKeyResult = AxiosResponse<CreateApiKeyResponse>
export type TenantApiKeysRevokeApiKeyResult = AxiosResponse<ApiKey>
export type TenantApiKeysRotateApiKeyResult = AxiosResponse<CreateApiKeyResponse>
export type TenantAuditListAuditEventsResult = AxiosResponse<TenantAuditListAuditEvents200>
export type TenantAuditListAuditEventsByUserResult = AxiosResponse<TenantAuditListAuditEventsByUser200>
export type TenantAuditExportAuditEventsResult = AxiosResponse<TenantAuditExportAuditEvents200>
export type TenantAuditGetRetentionPolicyResult = AxiosResponse<TenantAuditGetRetentionPolicy200>
export type TenantAuditSetRetentionPolicyResult = AxiosResponse<TenantAuditSetRetentionPolicy200>
export type TenantRolesListRolesResult = AxiosResponse<TenantRolesListRoles200>
export type TenantRolesCreateRoleResult = AxiosResponse<Role>
export type TenantRolesGetRoleResult = AxiosResponse<Role>
export type TenantRolesUpdateRoleResult = AxiosResponse<Role>
export type TenantRolesDeleteRoleResult = AxiosResponse<void>
export type TenantRoleMenusListRoleMenusResult = AxiosResponse<RoleMenuGrant>
export type TenantRoleMenusSetRoleMenusResult = AxiosResponse<RoleMenuGrant>
export type TenantRoleMenusClearRoleMenusResult = AxiosResponse<void>
export type TenantRolesSetPermissionsResult = AxiosResponse<Role>
export type TenantUsersListUsersResult = AxiosResponse<TenantUsersListUsers200>
export type TenantUsersCreateUserResult = AxiosResponse<User>
export type TenantUsersInviteUserResult = AxiosResponse<User>
export type TenantUsersGetUserResult = AxiosResponse<User>
export type TenantUsersUpdateUserResult = AxiosResponse<User>
export type TenantUsersDeleteUserResult = AxiosResponse<void>
export type TenantUsersAssignRolesResult = AxiosResponse<User>
export type TenantUsersChangeUserStatusResult = AxiosResponse<User>
