/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AdminClientsListClients200,
  AdminClientsListClientsParams,
  AdminClientsSetClientStatusBody,
  AdminTenantsListTenants200,
  AdminTenantsListTenantsParams,
  AuthorizeCodeRequest,
  ClientMenusMoveSysMenuBody,
  CreateOAuthClientRequest,
  CreateSysMenuRequest,
  CreateSysRoleRequest,
  CreateSysUserRequest,
  CreateTenantRequest,
  CurrentUser,
  LoginRequest,
  LoginResponse,
  MeGetMyMenus200,
  MeGetMyMenusParams,
  MeListMyTenantsParams,
  MeSwitchTenantParams,
  OAuthAuthorize200,
  OAuthClient,
  OAuthClientPublicInfo,
  OidcCallbackRequest,
  ReorderSysMenuRequest,
  SetSysRoleMenusRequest,
  SetTenantMemberRolesRequest,
  SubscribeTenantApplicationRequest,
  SwitchTenantResponse,
  SysMenu,
  SysRole,
  SysRoleMenu,
  Tenant,
  TenantApplication,
  TenantApplicationsListTenantApplications200,
  TenantApplicationsListTenantApplicationsParams,
  TenantMember,
  TenantMemberView,
  TenantMembersChangeTenantUserStatusBody,
  TenantMembersInviteTenantUserBody,
  TenantMembersListTenantUsers200,
  TenantMembersListTenantUsersParams,
  TenantRoleMenusClearSysRoleMenusParams,
  TenantRoleMenusListSysRoleMenusParams,
  TenantRoleMenusSetSysRoleMenusParams,
  TenantRolesListSysRoles200,
  TenantRolesListSysRolesParams,
  TokenRequest,
  TokenResponse,
  UpdateOAuthClientRequest,
  UpdateSysMenuRequest,
  UpdateSysRoleRequest,
  UpdateSysUserRequest,
  UpdateTenantApplicationRequest,
  UpdateTenantRequest
} from './handlers.msw.schemas';




  export const adminClientsListClients = <TData = AxiosResponse<AdminClientsListClients200>>(
    params?: AdminClientsListClientsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/admin/clients`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const adminClientsCreateClient = <TData = AxiosResponse<OAuthClient>>(
    createOAuthClientRequest: CreateOAuthClientRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/admin/clients`,
      createOAuthClientRequest,options
    );
  }

export const adminClientsGetClient = <TData = AxiosResponse<OAuthClient>>(
    clientId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/admin/clients/${clientId}`,options
    );
  }

export const adminClientsUpdateClient = <TData = AxiosResponse<OAuthClient>>(
    clientId: string,
    updateOAuthClientRequest: UpdateOAuthClientRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/v1/admin/clients/${clientId}`,
      updateOAuthClientRequest,options
    );
  }

export const adminClientsDeleteClient = <TData = AxiosResponse<void>>(
    clientId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/admin/clients/${clientId}`,options
    );
  }

export const adminClientsSetClientStatus = <TData = AxiosResponse<OAuthClient>>(
    clientId: string,
    adminClientsSetClientStatusBody: AdminClientsSetClientStatusBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/v1/admin/clients/${clientId}/status`,
      adminClientsSetClientStatusBody,options
    );
  }

export const adminTenantsListTenants = <TData = AxiosResponse<AdminTenantsListTenants200>>(
    params?: AdminTenantsListTenantsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/admin/tenants`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const adminTenantsCreateTenant = <TData = AxiosResponse<Tenant>>(
    createTenantRequest: CreateTenantRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/admin/tenants`,
      createTenantRequest,options
    );
  }

export const adminTenantsGetTenant = <TData = AxiosResponse<Tenant>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/admin/tenants/${id}`,options
    );
  }

export const adminTenantsUpdateTenant = <TData = AxiosResponse<Tenant>>(
    id: string,
    updateTenantRequest: UpdateTenantRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/v1/admin/tenants/${id}`,
      updateTenantRequest,options
    );
  }

export const adminTenantsDeleteTenant = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/admin/tenants/${id}`,options
    );
  }

export const sessionsLogin = <TData = AxiosResponse<LoginResponse>>(
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/auth/login`,
      loginRequest,options
    );
  }

export const sessionsLogout = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/auth/logout`,undefined,options
    );
  }

export const sessionsOidcCallback = <TData = AxiosResponse<TokenResponse>>(
    oidcCallbackRequest: OidcCallbackRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/auth/oidc/callback`,
      oidcCallbackRequest,options
    );
  }

export const sessionsRefreshToken = <TData = AxiosResponse<TokenResponse>>(
    tokenRequest: TokenRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/auth/refresh`,
      tokenRequest,options
    );
  }

export const clientsGetClient = <TData = AxiosResponse<OAuthClientPublicInfo>>(
    clientId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/clients/${clientId}`,options
    );
  }

export const clientMenusListSysMenus = <TData = AxiosResponse<SysMenu[]>>(
    clientId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/clients/${clientId}/menus`,options
    );
  }

export const clientMenusCreateSysMenu = <TData = AxiosResponse<SysMenu>>(
    clientId: string,
    createSysMenuRequest: CreateSysMenuRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/clients/${clientId}/menus`,
      createSysMenuRequest,options
    );
  }

export const clientMenusGetSysMenu = <TData = AxiosResponse<SysMenu>>(
    clientId: string,
    menuId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/clients/${clientId}/menus/${menuId}`,options
    );
  }

export const clientMenusUpdateSysMenu = <TData = AxiosResponse<SysMenu>>(
    clientId: string,
    menuId: string,
    updateSysMenuRequest: UpdateSysMenuRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/v1/clients/${clientId}/menus/${menuId}`,
      updateSysMenuRequest,options
    );
  }

export const clientMenusDeleteSysMenu = <TData = AxiosResponse<void>>(
    clientId: string,
    menuId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/clients/${clientId}/menus/${menuId}`,options
    );
  }

export const clientMenusMoveSysMenu = <TData = AxiosResponse<SysMenu>>(
    clientId: string,
    menuId: string,
    clientMenusMoveSysMenuBody: ClientMenusMoveSysMenuBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/v1/clients/${clientId}/menus/${menuId}/parent`,
      clientMenusMoveSysMenuBody,options
    );
  }

export const clientMenusReorderSysMenus = <TData = AxiosResponse<SysMenu[]>>(
    clientId: string,
    menuId: string,
    reorderSysMenuRequest: ReorderSysMenuRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/v1/clients/${clientId}/menus/${menuId}/reorder`,
      reorderSysMenuRequest,options
    );
  }

export const meWhoami = <TData = AxiosResponse<CurrentUser>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/me`,options
    );
  }

export const meGetMyMenus = <TData = AxiosResponse<MeGetMyMenus200>>(
    params: MeGetMyMenusParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/me/menus`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const meListMyTenants = <TData = AxiosResponse<TenantMember[]>>(
    params: MeListMyTenantsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/me/tenants`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const meSwitchTenant = <TData = AxiosResponse<SwitchTenantResponse>>(
    tenantId: string,
    params: MeSwitchTenantParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/me/tenants/${tenantId}/switch`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const oAuthAuthorize = <TData = AxiosResponse<OAuthAuthorize200>>(
    authorizeCodeRequest: AuthorizeCodeRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/oauth/authorize`,
      authorizeCodeRequest,options
    );
  }

export const oAuthToken = <TData = AxiosResponse<TokenResponse>>(
    tokenRequest: TokenRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/oauth/token`,
      tokenRequest,options
    );
  }

export const tenantApplicationsListTenantApplications = <TData = AxiosResponse<TenantApplicationsListTenantApplications200>>(
    tenantId: string,
    params?: TenantApplicationsListTenantApplicationsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/tenants/${tenantId}/applications`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const tenantApplicationsSubscribeTenantApplication = <TData = AxiosResponse<TenantApplication>>(
    tenantId: string,
    subscribeTenantApplicationRequest: SubscribeTenantApplicationRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/tenants/${tenantId}/applications`,
      subscribeTenantApplicationRequest,options
    );
  }

export const tenantApplicationsUpdateTenantApplication = <TData = AxiosResponse<TenantApplication>>(
    tenantId: string,
    clientId: string,
    updateTenantApplicationRequest: UpdateTenantApplicationRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/v1/tenants/${tenantId}/applications/${clientId}`,
      updateTenantApplicationRequest,options
    );
  }

export const tenantApplicationsRemoveTenantApplication = <TData = AxiosResponse<void>>(
    tenantId: string,
    clientId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/tenants/${tenantId}/applications/${clientId}`,options
    );
  }

export const tenantMembersListTenantUsers = <TData = AxiosResponse<TenantMembersListTenantUsers200>>(
    tenantId: string,
    params?: TenantMembersListTenantUsersParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/tenants/${tenantId}/members`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const tenantMembersCreateTenantUser = <TData = AxiosResponse<TenantMemberView>>(
    tenantId: string,
    createSysUserRequest: CreateSysUserRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/tenants/${tenantId}/members`,
      createSysUserRequest,options
    );
  }

export const tenantMembersInviteTenantUser = <TData = AxiosResponse<TenantMemberView>>(
    tenantId: string,
    tenantMembersInviteTenantUserBody: TenantMembersInviteTenantUserBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/tenants/${tenantId}/members/invitations`,
      tenantMembersInviteTenantUserBody,options
    );
  }

export const tenantMembersGetTenantUser = <TData = AxiosResponse<TenantMemberView>>(
    tenantId: string,
    userId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/tenants/${tenantId}/members/${userId}`,options
    );
  }

export const tenantMembersUpdateTenantUser = <TData = AxiosResponse<TenantMemberView>>(
    tenantId: string,
    userId: string,
    updateSysUserRequest: UpdateSysUserRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/v1/tenants/${tenantId}/members/${userId}`,
      updateSysUserRequest,options
    );
  }

export const tenantMembersDeleteTenantUser = <TData = AxiosResponse<void>>(
    tenantId: string,
    userId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/tenants/${tenantId}/members/${userId}`,options
    );
  }

export const tenantMembersAssignTenantMemberRoles = <TData = AxiosResponse<TenantMemberView>>(
    tenantId: string,
    userId: string,
    setTenantMemberRolesRequest: SetTenantMemberRolesRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/v1/tenants/${tenantId}/members/${userId}/roles`,
      setTenantMemberRolesRequest,options
    );
  }

export const tenantMembersChangeTenantUserStatus = <TData = AxiosResponse<TenantMemberView>>(
    tenantId: string,
    userId: string,
    tenantMembersChangeTenantUserStatusBody: TenantMembersChangeTenantUserStatusBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/v1/tenants/${tenantId}/members/${userId}/status`,
      tenantMembersChangeTenantUserStatusBody,options
    );
  }

export const tenantRolesListSysRoles = <TData = AxiosResponse<TenantRolesListSysRoles200>>(
    tenantId: string,
    params: TenantRolesListSysRolesParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/tenants/${tenantId}/roles`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const tenantRolesCreateSysRole = <TData = AxiosResponse<SysRole>>(
    tenantId: string,
    createSysRoleRequest: CreateSysRoleRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/tenants/${tenantId}/roles`,
      createSysRoleRequest,options
    );
  }

export const tenantRolesGetSysRole = <TData = AxiosResponse<SysRole>>(
    tenantId: string,
    roleId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/tenants/${tenantId}/roles/${roleId}`,options
    );
  }

export const tenantRolesUpdateSysRole = <TData = AxiosResponse<SysRole>>(
    tenantId: string,
    roleId: string,
    updateSysRoleRequest: UpdateSysRoleRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/v1/tenants/${tenantId}/roles/${roleId}`,
      updateSysRoleRequest,options
    );
  }

export const tenantRolesDeleteSysRole = <TData = AxiosResponse<void>>(
    tenantId: string,
    roleId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/tenants/${tenantId}/roles/${roleId}`,options
    );
  }

export const tenantRoleMenusListSysRoleMenus = <TData = AxiosResponse<SysRoleMenu[]>>(
    tenantId: string,
    roleId: string,
    params: TenantRoleMenusListSysRoleMenusParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/tenants/${tenantId}/roles/${roleId}/menus`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const tenantRoleMenusSetSysRoleMenus = <TData = AxiosResponse<SysRoleMenu[]>>(
    tenantId: string,
    roleId: string,
    setSysRoleMenusRequest: SetSysRoleMenusRequest,
    params: TenantRoleMenusSetSysRoleMenusParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/v1/tenants/${tenantId}/roles/${roleId}/menus`,
      setSysRoleMenusRequest,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const tenantRoleMenusClearSysRoleMenus = <TData = AxiosResponse<void>>(
    tenantId: string,
    roleId: string,
    params: TenantRoleMenusClearSysRoleMenusParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/tenants/${tenantId}/roles/${roleId}/menus`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export type AdminClientsListClientsResult = AxiosResponse<AdminClientsListClients200>
export type AdminClientsCreateClientResult = AxiosResponse<OAuthClient>
export type AdminClientsGetClientResult = AxiosResponse<OAuthClient>
export type AdminClientsUpdateClientResult = AxiosResponse<OAuthClient>
export type AdminClientsDeleteClientResult = AxiosResponse<void>
export type AdminClientsSetClientStatusResult = AxiosResponse<OAuthClient>
export type AdminTenantsListTenantsResult = AxiosResponse<AdminTenantsListTenants200>
export type AdminTenantsCreateTenantResult = AxiosResponse<Tenant>
export type AdminTenantsGetTenantResult = AxiosResponse<Tenant>
export type AdminTenantsUpdateTenantResult = AxiosResponse<Tenant>
export type AdminTenantsDeleteTenantResult = AxiosResponse<void>
export type SessionsLoginResult = AxiosResponse<LoginResponse>
export type SessionsLogoutResult = AxiosResponse<void>
export type SessionsOidcCallbackResult = AxiosResponse<TokenResponse>
export type SessionsRefreshTokenResult = AxiosResponse<TokenResponse>
export type ClientsGetClientResult = AxiosResponse<OAuthClientPublicInfo>
export type ClientMenusListSysMenusResult = AxiosResponse<SysMenu[]>
export type ClientMenusCreateSysMenuResult = AxiosResponse<SysMenu>
export type ClientMenusGetSysMenuResult = AxiosResponse<SysMenu>
export type ClientMenusUpdateSysMenuResult = AxiosResponse<SysMenu>
export type ClientMenusDeleteSysMenuResult = AxiosResponse<void>
export type ClientMenusMoveSysMenuResult = AxiosResponse<SysMenu>
export type ClientMenusReorderSysMenusResult = AxiosResponse<SysMenu[]>
export type MeWhoamiResult = AxiosResponse<CurrentUser>
export type MeGetMyMenusResult = AxiosResponse<MeGetMyMenus200>
export type MeListMyTenantsResult = AxiosResponse<TenantMember[]>
export type MeSwitchTenantResult = AxiosResponse<SwitchTenantResponse>
export type OAuthAuthorizeResult = AxiosResponse<OAuthAuthorize200>
export type OAuthTokenResult = AxiosResponse<TokenResponse>
export type TenantApplicationsListTenantApplicationsResult = AxiosResponse<TenantApplicationsListTenantApplications200>
export type TenantApplicationsSubscribeTenantApplicationResult = AxiosResponse<TenantApplication>
export type TenantApplicationsUpdateTenantApplicationResult = AxiosResponse<TenantApplication>
export type TenantApplicationsRemoveTenantApplicationResult = AxiosResponse<void>
export type TenantMembersListTenantUsersResult = AxiosResponse<TenantMembersListTenantUsers200>
export type TenantMembersCreateTenantUserResult = AxiosResponse<TenantMemberView>
export type TenantMembersInviteTenantUserResult = AxiosResponse<TenantMemberView>
export type TenantMembersGetTenantUserResult = AxiosResponse<TenantMemberView>
export type TenantMembersUpdateTenantUserResult = AxiosResponse<TenantMemberView>
export type TenantMembersDeleteTenantUserResult = AxiosResponse<void>
export type TenantMembersAssignTenantMemberRolesResult = AxiosResponse<TenantMemberView>
export type TenantMembersChangeTenantUserStatusResult = AxiosResponse<TenantMemberView>
export type TenantRolesListSysRolesResult = AxiosResponse<TenantRolesListSysRoles200>
export type TenantRolesCreateSysRoleResult = AxiosResponse<SysRole>
export type TenantRolesGetSysRoleResult = AxiosResponse<SysRole>
export type TenantRolesUpdateSysRoleResult = AxiosResponse<SysRole>
export type TenantRolesDeleteSysRoleResult = AxiosResponse<void>
export type TenantRoleMenusListSysRoleMenusResult = AxiosResponse<SysRoleMenu[]>
export type TenantRoleMenusSetSysRoleMenusResult = AxiosResponse<SysRoleMenu[]>
export type TenantRoleMenusClearSysRoleMenusResult = AxiosResponse<void>
