/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import {
  SysMenuType,
  SysUserStatus,
  TenantMemberStatus,
  TenantStatus
} from './handlers.msw.schemas';
import type {
  AdminClientsListClients200,
  AdminTenantsListTenants200,
  CurrentUser,
  LoginResponse,
  MeGetMyMenus200,
  OAuthAuthorize200,
  OAuthClient,
  OAuthClientPublicInfo,
  SwitchTenantResponse,
  SysMenu,
  SysRole,
  SysRoleMenu,
  Tenant,
  TenantApplication,
  TenantApplicationsListTenantApplications200,
  TenantMember,
  TenantMemberView,
  TenantMembersListTenantUsers200,
  TenantRolesListSysRoles200,
  TokenResponse
} from './handlers.msw.schemas';


export const getAdminClientsListClientsResponseMock = (overrideResponse: Partial< AdminClientsListClients200 > = {}): AdminClientsListClients200 => ({items: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), clientId: faker.string.alpha({length: {min: 10, max: 20}}), clientName: faker.string.alpha({length: {min: 10, max: 20}}), grantTypes: faker.string.alpha({length: {min: 10, max: 20}}), redirectUris: faker.string.alpha({length: {min: 10, max: 20}}), scopes: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), accessTokenValidity: faker.number.int({min: undefined, max: undefined}), refreshTokenValidity: faker.number.int({min: undefined, max: undefined}), autoApprove: faker.datatype.boolean(), status: faker.number.int({min: undefined, max: undefined}), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`})), page: faker.number.int({min: undefined, max: undefined}), pageSize: faker.number.int({min: undefined, max: undefined}), total: faker.number.int({min: undefined, max: undefined}), ...overrideResponse})

export const getAdminClientsCreateClientResponseMock = (overrideResponse: Partial< OAuthClient > = {}): OAuthClient => ({id: faker.string.uuid(), clientId: faker.string.alpha({length: {min: 10, max: 20}}), clientName: faker.string.alpha({length: {min: 10, max: 20}}), grantTypes: faker.string.alpha({length: {min: 10, max: 20}}), redirectUris: faker.string.alpha({length: {min: 10, max: 20}}), scopes: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), accessTokenValidity: faker.number.int({min: undefined, max: undefined}), refreshTokenValidity: faker.number.int({min: undefined, max: undefined}), autoApprove: faker.datatype.boolean(), status: faker.number.int({min: undefined, max: undefined}), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getAdminClientsGetClientResponseMock = (overrideResponse: Partial< OAuthClient > = {}): OAuthClient => ({id: faker.string.uuid(), clientId: faker.string.alpha({length: {min: 10, max: 20}}), clientName: faker.string.alpha({length: {min: 10, max: 20}}), grantTypes: faker.string.alpha({length: {min: 10, max: 20}}), redirectUris: faker.string.alpha({length: {min: 10, max: 20}}), scopes: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), accessTokenValidity: faker.number.int({min: undefined, max: undefined}), refreshTokenValidity: faker.number.int({min: undefined, max: undefined}), autoApprove: faker.datatype.boolean(), status: faker.number.int({min: undefined, max: undefined}), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getAdminClientsUpdateClientResponseMock = (overrideResponse: Partial< OAuthClient > = {}): OAuthClient => ({id: faker.string.uuid(), clientId: faker.string.alpha({length: {min: 10, max: 20}}), clientName: faker.string.alpha({length: {min: 10, max: 20}}), grantTypes: faker.string.alpha({length: {min: 10, max: 20}}), redirectUris: faker.string.alpha({length: {min: 10, max: 20}}), scopes: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), accessTokenValidity: faker.number.int({min: undefined, max: undefined}), refreshTokenValidity: faker.number.int({min: undefined, max: undefined}), autoApprove: faker.datatype.boolean(), status: faker.number.int({min: undefined, max: undefined}), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getAdminClientsSetClientStatusResponseMock = (overrideResponse: Partial< OAuthClient > = {}): OAuthClient => ({id: faker.string.uuid(), clientId: faker.string.alpha({length: {min: 10, max: 20}}), clientName: faker.string.alpha({length: {min: 10, max: 20}}), grantTypes: faker.string.alpha({length: {min: 10, max: 20}}), redirectUris: faker.string.alpha({length: {min: 10, max: 20}}), scopes: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), accessTokenValidity: faker.number.int({min: undefined, max: undefined}), refreshTokenValidity: faker.number.int({min: undefined, max: undefined}), autoApprove: faker.datatype.boolean(), status: faker.number.int({min: undefined, max: undefined}), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getAdminTenantsListTenantsResponseMock = (overrideResponse: Partial< AdminTenantsListTenants200 > = {}): AdminTenantsListTenants200 => ({items: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), tenantKey: faker.string.alpha({length: {min: 2, max: 64}}), name: faker.string.alpha({length: {min: 2, max: 128}}), status: faker.helpers.arrayElement(Object.values(TenantStatus)), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`})), page: faker.number.int({min: undefined, max: undefined}), pageSize: faker.number.int({min: undefined, max: undefined}), total: faker.number.int({min: undefined, max: undefined}), ...overrideResponse})

export const getAdminTenantsCreateTenantResponseMock = (overrideResponse: Partial< Tenant > = {}): Tenant => ({id: faker.string.uuid(), tenantKey: faker.string.alpha({length: {min: 2, max: 64}}), name: faker.string.alpha({length: {min: 2, max: 128}}), status: faker.helpers.arrayElement(Object.values(TenantStatus)), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getAdminTenantsGetTenantResponseMock = (overrideResponse: Partial< Tenant > = {}): Tenant => ({id: faker.string.uuid(), tenantKey: faker.string.alpha({length: {min: 2, max: 64}}), name: faker.string.alpha({length: {min: 2, max: 128}}), status: faker.helpers.arrayElement(Object.values(TenantStatus)), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getAdminTenantsUpdateTenantResponseMock = (overrideResponse: Partial< Tenant > = {}): Tenant => ({id: faker.string.uuid(), tenantKey: faker.string.alpha({length: {min: 2, max: 64}}), name: faker.string.alpha({length: {min: 2, max: 128}}), status: faker.helpers.arrayElement(Object.values(TenantStatus)), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getSessionsLoginResponseMock = (overrideResponse: Partial< LoginResponse > = {}): LoginResponse => ({user: {id: faker.string.uuid(), username: faker.string.alpha({length: {min: 1, max: 64}}), email: faker.helpers.arrayElement([faker.internet.email(), undefined]), mobile: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement(Object.values(SysUserStatus)), failedAttempts: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), lockedUntil: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined]), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`}, availableTenants: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), tenantId: faker.string.uuid(), userId: faker.string.uuid(), memberName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), isOwner: faker.datatype.boolean(), status: faker.helpers.arrayElement(Object.values(TenantMemberStatus)), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`})), accessToken: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), refreshToken: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), tokenType: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), expiresIn: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), clientId: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getSessionsOidcCallbackResponseMock = (overrideResponse: Partial< TokenResponse > = {}): TokenResponse => ({accessToken: faker.string.alpha({length: {min: 10, max: 20}}), refreshToken: faker.string.alpha({length: {min: 10, max: 20}}), tokenType: faker.string.alpha({length: {min: 10, max: 20}}), expiresIn: faker.number.int({min: undefined, max: undefined}), scope: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), userId: faker.string.alpha({length: {min: 10, max: 20}}), clientId: faker.string.alpha({length: {min: 10, max: 20}}), tenantId: faker.string.uuid(), ...overrideResponse})

export const getSessionsRefreshTokenResponseMock = (overrideResponse: Partial< TokenResponse > = {}): TokenResponse => ({accessToken: faker.string.alpha({length: {min: 10, max: 20}}), refreshToken: faker.string.alpha({length: {min: 10, max: 20}}), tokenType: faker.string.alpha({length: {min: 10, max: 20}}), expiresIn: faker.number.int({min: undefined, max: undefined}), scope: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), userId: faker.string.alpha({length: {min: 10, max: 20}}), clientId: faker.string.alpha({length: {min: 10, max: 20}}), tenantId: faker.string.uuid(), ...overrideResponse})

export const getClientsGetClientResponseMock = (overrideResponse: Partial< OAuthClientPublicInfo > = {}): OAuthClientPublicInfo => ({clientId: faker.string.alpha({length: {min: 10, max: 20}}), clientName: faker.string.alpha({length: {min: 10, max: 20}}), status: faker.number.int({min: undefined, max: undefined}), ...overrideResponse})

export const getClientMenusListSysMenusResponseMock = (): SysMenu[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), clientId: faker.string.alpha({length: {min: 10, max: 20}}), parentId: faker.string.uuid(), title: faker.string.alpha({length: {min: 10, max: 20}}), type: faker.helpers.arrayElement(Object.values(SysMenuType)), path: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), component: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), perms: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), icon: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), sortOrder: faker.number.int({min: undefined, max: undefined}), status: faker.number.int({min: undefined, max: undefined}), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`})))

export const getClientMenusCreateSysMenuResponseMock = (overrideResponse: Partial< SysMenu > = {}): SysMenu => ({id: faker.string.uuid(), clientId: faker.string.alpha({length: {min: 10, max: 20}}), parentId: faker.string.uuid(), title: faker.string.alpha({length: {min: 10, max: 20}}), type: faker.helpers.arrayElement(Object.values(SysMenuType)), path: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), component: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), perms: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), icon: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), sortOrder: faker.number.int({min: undefined, max: undefined}), status: faker.number.int({min: undefined, max: undefined}), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getClientMenusGetSysMenuResponseMock = (overrideResponse: Partial< SysMenu > = {}): SysMenu => ({id: faker.string.uuid(), clientId: faker.string.alpha({length: {min: 10, max: 20}}), parentId: faker.string.uuid(), title: faker.string.alpha({length: {min: 10, max: 20}}), type: faker.helpers.arrayElement(Object.values(SysMenuType)), path: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), component: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), perms: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), icon: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), sortOrder: faker.number.int({min: undefined, max: undefined}), status: faker.number.int({min: undefined, max: undefined}), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getClientMenusUpdateSysMenuResponseMock = (overrideResponse: Partial< SysMenu > = {}): SysMenu => ({id: faker.string.uuid(), clientId: faker.string.alpha({length: {min: 10, max: 20}}), parentId: faker.string.uuid(), title: faker.string.alpha({length: {min: 10, max: 20}}), type: faker.helpers.arrayElement(Object.values(SysMenuType)), path: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), component: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), perms: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), icon: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), sortOrder: faker.number.int({min: undefined, max: undefined}), status: faker.number.int({min: undefined, max: undefined}), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getClientMenusMoveSysMenuResponseMock = (overrideResponse: Partial< SysMenu > = {}): SysMenu => ({id: faker.string.uuid(), clientId: faker.string.alpha({length: {min: 10, max: 20}}), parentId: faker.string.uuid(), title: faker.string.alpha({length: {min: 10, max: 20}}), type: faker.helpers.arrayElement(Object.values(SysMenuType)), path: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), component: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), perms: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), icon: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), sortOrder: faker.number.int({min: undefined, max: undefined}), status: faker.number.int({min: undefined, max: undefined}), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getClientMenusReorderSysMenusResponseMock = (): SysMenu[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), clientId: faker.string.alpha({length: {min: 10, max: 20}}), parentId: faker.string.uuid(), title: faker.string.alpha({length: {min: 10, max: 20}}), type: faker.helpers.arrayElement(Object.values(SysMenuType)), path: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), component: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), perms: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), icon: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), sortOrder: faker.number.int({min: undefined, max: undefined}), status: faker.number.int({min: undefined, max: undefined}), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`})))

export const getMeWhoamiResponseMock = (overrideResponse: Partial< CurrentUser > = {}): CurrentUser => ({user: {id: faker.string.uuid(), username: faker.string.alpha({length: {min: 1, max: 64}}), email: faker.helpers.arrayElement([faker.internet.email(), undefined]), mobile: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement(Object.values(SysUserStatus)), failedAttempts: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), lockedUntil: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined]), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`}, memberships: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), tenantId: faker.string.uuid(), userId: faker.string.uuid(), memberName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), isOwner: faker.datatype.boolean(), status: faker.helpers.arrayElement(Object.values(TenantMemberStatus)), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`})), currentTenantId: faker.helpers.arrayElement([faker.string.uuid(), undefined]), clientId: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})

export const getMeGetMyMenusResponseMock = (): MeGetMyMenus200 => ({
        [faker.string.alphanumeric(5)]: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), clientId: faker.string.alpha({length: {min: 10, max: 20}}), parentId: faker.string.uuid(), title: faker.string.alpha({length: {min: 10, max: 20}}), type: faker.helpers.arrayElement(Object.values(SysMenuType)), path: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), component: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), perms: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), icon: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), sortOrder: faker.number.int({min: undefined, max: undefined}), children: []}))
      })

export const getMeListMyTenantsResponseMock = (): TenantMember[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), tenantId: faker.string.uuid(), userId: faker.string.uuid(), memberName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), isOwner: faker.datatype.boolean(), status: faker.helpers.arrayElement(Object.values(TenantMemberStatus)), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`})))

export const getMeSwitchTenantResponseMock = (overrideResponse: Partial< SwitchTenantResponse > = {}): SwitchTenantResponse => ({accessToken: faker.string.alpha({length: {min: 10, max: 20}}), refreshToken: faker.string.alpha({length: {min: 10, max: 20}}), expiresAt: `${faker.date.past().toISOString().split('.')[0]}Z`, tenantId: faker.string.uuid(), clientId: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getOAuthAuthorizeResponseMock = (overrideResponse: Partial< OAuthAuthorize200 > = {}): OAuthAuthorize200 => ({code: faker.string.alpha({length: {min: 10, max: 20}}), state: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getOAuthTokenResponseMock = (overrideResponse: Partial< TokenResponse > = {}): TokenResponse => ({accessToken: faker.string.alpha({length: {min: 10, max: 20}}), refreshToken: faker.string.alpha({length: {min: 10, max: 20}}), tokenType: faker.string.alpha({length: {min: 10, max: 20}}), expiresIn: faker.number.int({min: undefined, max: undefined}), scope: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), userId: faker.string.alpha({length: {min: 10, max: 20}}), clientId: faker.string.alpha({length: {min: 10, max: 20}}), tenantId: faker.string.uuid(), ...overrideResponse})

export const getTenantApplicationsListTenantApplicationsResponseMock = (overrideResponse: Partial< TenantApplicationsListTenantApplications200 > = {}): TenantApplicationsListTenantApplications200 => ({items: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), tenantId: faker.string.uuid(), clientId: faker.string.alpha({length: {min: 10, max: 20}}), status: faker.number.int({min: undefined, max: undefined}), expireTime: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined]), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`})), page: faker.number.int({min: undefined, max: undefined}), pageSize: faker.number.int({min: undefined, max: undefined}), total: faker.number.int({min: undefined, max: undefined}), ...overrideResponse})

export const getTenantApplicationsSubscribeTenantApplicationResponseMock = (overrideResponse: Partial< TenantApplication > = {}): TenantApplication => ({id: faker.string.uuid(), tenantId: faker.string.uuid(), clientId: faker.string.alpha({length: {min: 10, max: 20}}), status: faker.number.int({min: undefined, max: undefined}), expireTime: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined]), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getTenantApplicationsUpdateTenantApplicationResponseMock = (overrideResponse: Partial< TenantApplication > = {}): TenantApplication => ({id: faker.string.uuid(), tenantId: faker.string.uuid(), clientId: faker.string.alpha({length: {min: 10, max: 20}}), status: faker.number.int({min: undefined, max: undefined}), expireTime: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined]), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getTenantMembersListTenantUsersResponseMock = (overrideResponse: Partial< TenantMembersListTenantUsers200 > = {}): TenantMembersListTenantUsers200 => ({items: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({member: {id: faker.string.uuid(), tenantId: faker.string.uuid(), userId: faker.string.uuid(), memberName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), isOwner: faker.datatype.boolean(), status: faker.helpers.arrayElement(Object.values(TenantMemberStatus)), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`}, user: {id: faker.string.uuid(), username: faker.string.alpha({length: {min: 1, max: 64}}), email: faker.helpers.arrayElement([faker.internet.email(), undefined]), mobile: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement(Object.values(SysUserStatus)), failedAttempts: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), lockedUntil: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined]), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`}, roles: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}})))})), page: faker.number.int({min: undefined, max: undefined}), pageSize: faker.number.int({min: undefined, max: undefined}), total: faker.number.int({min: undefined, max: undefined}), ...overrideResponse})

export const getTenantMembersCreateTenantUserResponseMock = (overrideResponse: Partial< TenantMemberView > = {}): TenantMemberView => ({member: {id: faker.string.uuid(), tenantId: faker.string.uuid(), userId: faker.string.uuid(), memberName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), isOwner: faker.datatype.boolean(), status: faker.helpers.arrayElement(Object.values(TenantMemberStatus)), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`}, user: {id: faker.string.uuid(), username: faker.string.alpha({length: {min: 1, max: 64}}), email: faker.helpers.arrayElement([faker.internet.email(), undefined]), mobile: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement(Object.values(SysUserStatus)), failedAttempts: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), lockedUntil: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined]), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`}, roles: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), ...overrideResponse})

export const getTenantMembersInviteTenantUserResponseMock = (overrideResponse: Partial< TenantMemberView > = {}): TenantMemberView => ({member: {id: faker.string.uuid(), tenantId: faker.string.uuid(), userId: faker.string.uuid(), memberName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), isOwner: faker.datatype.boolean(), status: faker.helpers.arrayElement(Object.values(TenantMemberStatus)), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`}, user: {id: faker.string.uuid(), username: faker.string.alpha({length: {min: 1, max: 64}}), email: faker.helpers.arrayElement([faker.internet.email(), undefined]), mobile: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement(Object.values(SysUserStatus)), failedAttempts: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), lockedUntil: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined]), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`}, roles: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), ...overrideResponse})

export const getTenantMembersGetTenantUserResponseMock = (overrideResponse: Partial< TenantMemberView > = {}): TenantMemberView => ({member: {id: faker.string.uuid(), tenantId: faker.string.uuid(), userId: faker.string.uuid(), memberName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), isOwner: faker.datatype.boolean(), status: faker.helpers.arrayElement(Object.values(TenantMemberStatus)), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`}, user: {id: faker.string.uuid(), username: faker.string.alpha({length: {min: 1, max: 64}}), email: faker.helpers.arrayElement([faker.internet.email(), undefined]), mobile: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement(Object.values(SysUserStatus)), failedAttempts: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), lockedUntil: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined]), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`}, roles: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), ...overrideResponse})

export const getTenantMembersUpdateTenantUserResponseMock = (overrideResponse: Partial< TenantMemberView > = {}): TenantMemberView => ({member: {id: faker.string.uuid(), tenantId: faker.string.uuid(), userId: faker.string.uuid(), memberName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), isOwner: faker.datatype.boolean(), status: faker.helpers.arrayElement(Object.values(TenantMemberStatus)), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`}, user: {id: faker.string.uuid(), username: faker.string.alpha({length: {min: 1, max: 64}}), email: faker.helpers.arrayElement([faker.internet.email(), undefined]), mobile: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement(Object.values(SysUserStatus)), failedAttempts: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), lockedUntil: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined]), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`}, roles: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), ...overrideResponse})

export const getTenantMembersAssignTenantMemberRolesResponseMock = (overrideResponse: Partial< TenantMemberView > = {}): TenantMemberView => ({member: {id: faker.string.uuid(), tenantId: faker.string.uuid(), userId: faker.string.uuid(), memberName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), isOwner: faker.datatype.boolean(), status: faker.helpers.arrayElement(Object.values(TenantMemberStatus)), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`}, user: {id: faker.string.uuid(), username: faker.string.alpha({length: {min: 1, max: 64}}), email: faker.helpers.arrayElement([faker.internet.email(), undefined]), mobile: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement(Object.values(SysUserStatus)), failedAttempts: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), lockedUntil: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined]), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`}, roles: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), ...overrideResponse})

export const getTenantMembersChangeTenantUserStatusResponseMock = (overrideResponse: Partial< TenantMemberView > = {}): TenantMemberView => ({member: {id: faker.string.uuid(), tenantId: faker.string.uuid(), userId: faker.string.uuid(), memberName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), isOwner: faker.datatype.boolean(), status: faker.helpers.arrayElement(Object.values(TenantMemberStatus)), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`}, user: {id: faker.string.uuid(), username: faker.string.alpha({length: {min: 1, max: 64}}), email: faker.helpers.arrayElement([faker.internet.email(), undefined]), mobile: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement(Object.values(SysUserStatus)), failedAttempts: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), lockedUntil: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined]), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`}, roles: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), ...overrideResponse})

export const getTenantRolesListSysRolesResponseMock = (overrideResponse: Partial< TenantRolesListSysRoles200 > = {}): TenantRolesListSysRoles200 => ({items: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), tenantId: faker.string.uuid(), clientId: faker.string.alpha({length: {min: 10, max: 20}}), roleCode: faker.string.alpha({length: {min: 1, max: 64}}), roleName: faker.string.alpha({length: {min: 1, max: 64}}), description: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), isPreset: faker.datatype.boolean(), status: faker.number.int({min: undefined, max: undefined}), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`})), page: faker.number.int({min: undefined, max: undefined}), pageSize: faker.number.int({min: undefined, max: undefined}), total: faker.number.int({min: undefined, max: undefined}), ...overrideResponse})

export const getTenantRolesCreateSysRoleResponseMock = (overrideResponse: Partial< SysRole > = {}): SysRole => ({id: faker.string.uuid(), tenantId: faker.string.uuid(), clientId: faker.string.alpha({length: {min: 10, max: 20}}), roleCode: faker.string.alpha({length: {min: 1, max: 64}}), roleName: faker.string.alpha({length: {min: 1, max: 64}}), description: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), isPreset: faker.datatype.boolean(), status: faker.number.int({min: undefined, max: undefined}), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getTenantRolesGetSysRoleResponseMock = (overrideResponse: Partial< SysRole > = {}): SysRole => ({id: faker.string.uuid(), tenantId: faker.string.uuid(), clientId: faker.string.alpha({length: {min: 10, max: 20}}), roleCode: faker.string.alpha({length: {min: 1, max: 64}}), roleName: faker.string.alpha({length: {min: 1, max: 64}}), description: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), isPreset: faker.datatype.boolean(), status: faker.number.int({min: undefined, max: undefined}), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getTenantRolesUpdateSysRoleResponseMock = (overrideResponse: Partial< SysRole > = {}): SysRole => ({id: faker.string.uuid(), tenantId: faker.string.uuid(), clientId: faker.string.alpha({length: {min: 10, max: 20}}), roleCode: faker.string.alpha({length: {min: 1, max: 64}}), roleName: faker.string.alpha({length: {min: 1, max: 64}}), description: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), isPreset: faker.datatype.boolean(), status: faker.number.int({min: undefined, max: undefined}), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getTenantRoleMenusListSysRoleMenusResponseMock = (): SysRoleMenu[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({roleId: faker.string.uuid(), menuId: faker.string.uuid()})))

export const getTenantRoleMenusSetSysRoleMenusResponseMock = (): SysRoleMenu[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({roleId: faker.string.uuid(), menuId: faker.string.uuid()})))


export const getAdminClientsListClientsMockHandler = (overrideResponse?: AdminClientsListClients200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<AdminClientsListClients200> | AdminClientsListClients200), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/admin/clients', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getAdminClientsListClientsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getAdminClientsCreateClientMockHandler = (overrideResponse?: OAuthClient | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<OAuthClient> | OAuthClient), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/admin/clients', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getAdminClientsCreateClientResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getAdminClientsGetClientMockHandler = (overrideResponse?: OAuthClient | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<OAuthClient> | OAuthClient), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/admin/clients/:clientId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getAdminClientsGetClientResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getAdminClientsUpdateClientMockHandler = (overrideResponse?: OAuthClient | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<OAuthClient> | OAuthClient), options?: RequestHandlerOptions) => {
  return http.patch('*/api/v1/admin/clients/:clientId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getAdminClientsUpdateClientResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getAdminClientsDeleteClientMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/v1/admin/clients/:clientId', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 204,
        
      })
  }, options)
}

export const getAdminClientsSetClientStatusMockHandler = (overrideResponse?: OAuthClient | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<OAuthClient> | OAuthClient), options?: RequestHandlerOptions) => {
  return http.patch('*/api/v1/admin/clients/:clientId/status', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getAdminClientsSetClientStatusResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getAdminTenantsListTenantsMockHandler = (overrideResponse?: AdminTenantsListTenants200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<AdminTenantsListTenants200> | AdminTenantsListTenants200), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/admin/tenants', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getAdminTenantsListTenantsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getAdminTenantsCreateTenantMockHandler = (overrideResponse?: Tenant | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Tenant> | Tenant), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/admin/tenants', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getAdminTenantsCreateTenantResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getAdminTenantsGetTenantMockHandler = (overrideResponse?: Tenant | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Tenant> | Tenant), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/admin/tenants/:id', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getAdminTenantsGetTenantResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getAdminTenantsUpdateTenantMockHandler = (overrideResponse?: Tenant | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<Tenant> | Tenant), options?: RequestHandlerOptions) => {
  return http.patch('*/api/v1/admin/tenants/:id', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getAdminTenantsUpdateTenantResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getAdminTenantsDeleteTenantMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/v1/admin/tenants/:id', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 204,
        
      })
  }, options)
}

export const getSessionsLoginMockHandler = (overrideResponse?: LoginResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<LoginResponse> | LoginResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/auth/login', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getSessionsLoginResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getSessionsLogoutMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/auth/logout', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 204,
        
      })
  }, options)
}

export const getSessionsOidcCallbackMockHandler = (overrideResponse?: TokenResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<TokenResponse> | TokenResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/auth/oidc/callback', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getSessionsOidcCallbackResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getSessionsRefreshTokenMockHandler = (overrideResponse?: TokenResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<TokenResponse> | TokenResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/auth/refresh', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getSessionsRefreshTokenResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getClientsGetClientMockHandler = (overrideResponse?: OAuthClientPublicInfo | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<OAuthClientPublicInfo> | OAuthClientPublicInfo), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/clients/:clientId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getClientsGetClientResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getClientMenusListSysMenusMockHandler = (overrideResponse?: SysMenu[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<SysMenu[]> | SysMenu[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/clients/:clientId/menus', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getClientMenusListSysMenusResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getClientMenusCreateSysMenuMockHandler = (overrideResponse?: SysMenu | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<SysMenu> | SysMenu), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/clients/:clientId/menus', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getClientMenusCreateSysMenuResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getClientMenusGetSysMenuMockHandler = (overrideResponse?: SysMenu | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<SysMenu> | SysMenu), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/clients/:clientId/menus/:menuId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getClientMenusGetSysMenuResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getClientMenusUpdateSysMenuMockHandler = (overrideResponse?: SysMenu | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<SysMenu> | SysMenu), options?: RequestHandlerOptions) => {
  return http.patch('*/api/v1/clients/:clientId/menus/:menuId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getClientMenusUpdateSysMenuResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getClientMenusDeleteSysMenuMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/v1/clients/:clientId/menus/:menuId', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 204,
        
      })
  }, options)
}

export const getClientMenusMoveSysMenuMockHandler = (overrideResponse?: SysMenu | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<SysMenu> | SysMenu), options?: RequestHandlerOptions) => {
  return http.patch('*/api/v1/clients/:clientId/menus/:menuId/parent', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getClientMenusMoveSysMenuResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getClientMenusReorderSysMenusMockHandler = (overrideResponse?: SysMenu[] | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<SysMenu[]> | SysMenu[]), options?: RequestHandlerOptions) => {
  return http.put('*/api/v1/clients/:clientId/menus/:menuId/reorder', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getClientMenusReorderSysMenusResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getMeWhoamiMockHandler = (overrideResponse?: CurrentUser | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CurrentUser> | CurrentUser), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/me', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getMeWhoamiResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getMeGetMyMenusMockHandler = (overrideResponse?: MeGetMyMenus200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<MeGetMyMenus200> | MeGetMyMenus200), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/me/menus', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getMeGetMyMenusResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getMeListMyTenantsMockHandler = (overrideResponse?: TenantMember[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<TenantMember[]> | TenantMember[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/me/tenants', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getMeListMyTenantsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getMeSwitchTenantMockHandler = (overrideResponse?: SwitchTenantResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<SwitchTenantResponse> | SwitchTenantResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/me/tenants/:tenantId/switch', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getMeSwitchTenantResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getOAuthAuthorizeMockHandler = (overrideResponse?: OAuthAuthorize200 | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<OAuthAuthorize200> | OAuthAuthorize200), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/oauth/authorize', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getOAuthAuthorizeResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getOAuthTokenMockHandler = (overrideResponse?: TokenResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<TokenResponse> | TokenResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/oauth/token', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getOAuthTokenResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getTenantApplicationsListTenantApplicationsMockHandler = (overrideResponse?: TenantApplicationsListTenantApplications200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<TenantApplicationsListTenantApplications200> | TenantApplicationsListTenantApplications200), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/tenants/:tenantId/applications', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getTenantApplicationsListTenantApplicationsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getTenantApplicationsSubscribeTenantApplicationMockHandler = (overrideResponse?: TenantApplication | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<TenantApplication> | TenantApplication), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/tenants/:tenantId/applications', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getTenantApplicationsSubscribeTenantApplicationResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getTenantApplicationsUpdateTenantApplicationMockHandler = (overrideResponse?: TenantApplication | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<TenantApplication> | TenantApplication), options?: RequestHandlerOptions) => {
  return http.patch('*/api/v1/tenants/:tenantId/applications/:clientId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getTenantApplicationsUpdateTenantApplicationResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getTenantApplicationsRemoveTenantApplicationMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/v1/tenants/:tenantId/applications/:clientId', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 204,
        
      })
  }, options)
}

export const getTenantMembersListTenantUsersMockHandler = (overrideResponse?: TenantMembersListTenantUsers200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<TenantMembersListTenantUsers200> | TenantMembersListTenantUsers200), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/tenants/:tenantId/members', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getTenantMembersListTenantUsersResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getTenantMembersCreateTenantUserMockHandler = (overrideResponse?: TenantMemberView | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<TenantMemberView> | TenantMemberView), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/tenants/:tenantId/members', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getTenantMembersCreateTenantUserResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getTenantMembersInviteTenantUserMockHandler = (overrideResponse?: TenantMemberView | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<TenantMemberView> | TenantMemberView), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/tenants/:tenantId/members/invitations', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getTenantMembersInviteTenantUserResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getTenantMembersGetTenantUserMockHandler = (overrideResponse?: TenantMemberView | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<TenantMemberView> | TenantMemberView), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/tenants/:tenantId/members/:userId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getTenantMembersGetTenantUserResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getTenantMembersUpdateTenantUserMockHandler = (overrideResponse?: TenantMemberView | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<TenantMemberView> | TenantMemberView), options?: RequestHandlerOptions) => {
  return http.patch('*/api/v1/tenants/:tenantId/members/:userId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getTenantMembersUpdateTenantUserResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getTenantMembersDeleteTenantUserMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/v1/tenants/:tenantId/members/:userId', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 204,
        
      })
  }, options)
}

export const getTenantMembersAssignTenantMemberRolesMockHandler = (overrideResponse?: TenantMemberView | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<TenantMemberView> | TenantMemberView), options?: RequestHandlerOptions) => {
  return http.put('*/api/v1/tenants/:tenantId/members/:userId/roles', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getTenantMembersAssignTenantMemberRolesResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getTenantMembersChangeTenantUserStatusMockHandler = (overrideResponse?: TenantMemberView | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<TenantMemberView> | TenantMemberView), options?: RequestHandlerOptions) => {
  return http.patch('*/api/v1/tenants/:tenantId/members/:userId/status', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getTenantMembersChangeTenantUserStatusResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getTenantRolesListSysRolesMockHandler = (overrideResponse?: TenantRolesListSysRoles200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<TenantRolesListSysRoles200> | TenantRolesListSysRoles200), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/tenants/:tenantId/roles', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getTenantRolesListSysRolesResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getTenantRolesCreateSysRoleMockHandler = (overrideResponse?: SysRole | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<SysRole> | SysRole), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/tenants/:tenantId/roles', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getTenantRolesCreateSysRoleResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getTenantRolesGetSysRoleMockHandler = (overrideResponse?: SysRole | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<SysRole> | SysRole), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/tenants/:tenantId/roles/:roleId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getTenantRolesGetSysRoleResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getTenantRolesUpdateSysRoleMockHandler = (overrideResponse?: SysRole | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<SysRole> | SysRole), options?: RequestHandlerOptions) => {
  return http.patch('*/api/v1/tenants/:tenantId/roles/:roleId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getTenantRolesUpdateSysRoleResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getTenantRolesDeleteSysRoleMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/v1/tenants/:tenantId/roles/:roleId', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 204,
        
      })
  }, options)
}

export const getTenantRoleMenusListSysRoleMenusMockHandler = (overrideResponse?: SysRoleMenu[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<SysRoleMenu[]> | SysRoleMenu[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/tenants/:tenantId/roles/:roleId/menus', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getTenantRoleMenusListSysRoleMenusResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getTenantRoleMenusSetSysRoleMenusMockHandler = (overrideResponse?: SysRoleMenu[] | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<SysRoleMenu[]> | SysRoleMenu[]), options?: RequestHandlerOptions) => {
  return http.put('*/api/v1/tenants/:tenantId/roles/:roleId/menus', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getTenantRoleMenusSetSysRoleMenusResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getTenantRoleMenusClearSysRoleMenusMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/v1/tenants/:tenantId/roles/:roleId/menus', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 204,
        
      })
  }, options)
}
export const getTitleMock = () => [
  getAdminClientsListClientsMockHandler(),
  getAdminClientsCreateClientMockHandler(),
  getAdminClientsGetClientMockHandler(),
  getAdminClientsUpdateClientMockHandler(),
  getAdminClientsDeleteClientMockHandler(),
  getAdminClientsSetClientStatusMockHandler(),
  getAdminTenantsListTenantsMockHandler(),
  getAdminTenantsCreateTenantMockHandler(),
  getAdminTenantsGetTenantMockHandler(),
  getAdminTenantsUpdateTenantMockHandler(),
  getAdminTenantsDeleteTenantMockHandler(),
  getSessionsLoginMockHandler(),
  getSessionsLogoutMockHandler(),
  getSessionsOidcCallbackMockHandler(),
  getSessionsRefreshTokenMockHandler(),
  getClientsGetClientMockHandler(),
  getClientMenusListSysMenusMockHandler(),
  getClientMenusCreateSysMenuMockHandler(),
  getClientMenusGetSysMenuMockHandler(),
  getClientMenusUpdateSysMenuMockHandler(),
  getClientMenusDeleteSysMenuMockHandler(),
  getClientMenusMoveSysMenuMockHandler(),
  getClientMenusReorderSysMenusMockHandler(),
  getMeWhoamiMockHandler(),
  getMeGetMyMenusMockHandler(),
  getMeListMyTenantsMockHandler(),
  getMeSwitchTenantMockHandler(),
  getOAuthAuthorizeMockHandler(),
  getOAuthTokenMockHandler(),
  getTenantApplicationsListTenantApplicationsMockHandler(),
  getTenantApplicationsSubscribeTenantApplicationMockHandler(),
  getTenantApplicationsUpdateTenantApplicationMockHandler(),
  getTenantApplicationsRemoveTenantApplicationMockHandler(),
  getTenantMembersListTenantUsersMockHandler(),
  getTenantMembersCreateTenantUserMockHandler(),
  getTenantMembersInviteTenantUserMockHandler(),
  getTenantMembersGetTenantUserMockHandler(),
  getTenantMembersUpdateTenantUserMockHandler(),
  getTenantMembersDeleteTenantUserMockHandler(),
  getTenantMembersAssignTenantMemberRolesMockHandler(),
  getTenantMembersChangeTenantUserStatusMockHandler(),
  getTenantRolesListSysRolesMockHandler(),
  getTenantRolesCreateSysRoleMockHandler(),
  getTenantRolesGetSysRoleMockHandler(),
  getTenantRolesUpdateSysRoleMockHandler(),
  getTenantRolesDeleteSysRoleMockHandler(),
  getTenantRoleMenusListSysRoleMenusMockHandler(),
  getTenantRoleMenusSetSysRoleMenusMockHandler(),
  getTenantRoleMenusClearSysRoleMenusMockHandler()]
